### ISSUE TITLE
Image Picker 이름 정하기

### ISSUE THREAD

**Issue by kklyoon** [sabujak-sabujak/Documentation#1]
생각나는데로 댓글을 달아봅시다. 심플하면 더 좋을것 같아요. 아무 단어 적어봅니다.

* Cherry Picker
* 호미 ( Homi )
* 뀰 ( GGul )
* 갈고리 ( Galgori )
* 맛동산 ( Matdonsan )
* 오뚜기 ( Oddugi )
* 고구마 ( GoGuma )
* 감자 ( Gamja )
* 메뚜기 ( Meddugi )
* 노각 ( NoGak )
* 우거지 ( Ugeoji )
* 달래 ( Dallae )
* 삼겹살 ( Samgyeobsal )
* 안심 ( Ansim )

**Comment by sangcomz** [comment]
엘레베이터 앞에서 말씀하셨던 피클 (Pickle) 도 좋았던것같아요

**Comment by Charlezz** [comment]
저도 HomiPicker,CherryPicker, PicklePicker 좋습니다.

이런것도 좋을것같아요.

SickPicker : 멋있는 피커
AwesomePicker : 쩌는 피커
DopePicker : 오지는 피커

**Comment by kklyoon** [comment]
피클피커보다 그냥 피클로 하는게 심플한거 같아요 ㅎㅎ

**Comment by dotkebi** [comment]
요럴땐 피클피클 이런 것도 나쁘지 않던데요 ㅎ

**Comment by kklyoon** [comment]
Pickle 로 결정되었습니다!!!
